name: Build

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created

permissions: {}
jobs:

  build_android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_opts:
          - ANDROID=1
    env:
      USE_CCACHE: 1
      CCACHE_EXEC: /usr/bin/ccache
      NDK_CCACHE: /usr/bin/ccache
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
          submodules: true
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py --build-opts "${{ matrix.build_opts }}"
        working-directory: .github/workflows
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6 # known to work
      - name: "Setup ccache: clear stats"
        run: ccache --zero-stats
      - run: make -j$(nproc) ${{ matrix.build_opts }} android
        working-directory: crawl-ref/source
      - name: Run gradle
        run: gradle :app:assembleBuildTest
        working-directory: crawl-ref/source/android-project
      - name: Print ccache stats
        run: ccache -p -s

