name: Build

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created

permissions: {}
jobs:
  linting:
    permissions:
      contents: read #  to fetch code (actions/checkout)

    name: Source Packages ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git fetch --tags
      - name: GIT STATUS
        run: git status
      - name: GIT DESCRIBE
        run: git describe
