name: Build

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created

permissions: {}
jobs:

  build_android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_opts:
          - ANDROID=1
    env:
      USE_CCACHE: 1
      CCACHE_EXEC: /usr/bin/ccache
      NDK_CCACHE: /usr/bin/ccache
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
          submodules: true
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py --build-opts "${{ matrix.build_opts }}"
        working-directory: .github/workflows
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5 # known to work
          cache-disabled: true
      - name: Cache compilation
        uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: ccache-android-${{ github.sha }}
          restore-keys: |
            ccache-android-
      - name: Setup ccache
        uses: alexjurkiewicz/setup-ccache@master
      - name: "Setup ccache: prepend path"
        run: "echo /usr/lib/ccache >> $GITHUB_PATH"
      - name: "Setup ccache: update symlinks"
        run: "/usr/sbin/update-ccache-symlinks"
      - name: "Setup ccache: clear stats"
        run: ccache --zero-stats
      - name: Prepare Android build
        run: make -j$(nproc) ${{ matrix.build_opts }} android
        working-directory: crawl-ref/source
      - name: Build with Gradle
        run: gradle :app:assembleBuildTest
        working-directory: crawl-ref/source/android-project
      - name: Print ccache stats
        run: ccache -p -s

